---
# yamllint configuration for rke2-node-init
# https://yamllint.readthedocs.io/en/stable/configuration.html

extends: default

rules:
  line-length:
    max: 120
    level: warning
  
  indentation:
    spaces: 2
    indent-sequences: true
  
  comments:
    min-spaces-from-content: 1
  
  comments-indentation: {}
  
  document-start:
    present: false
  
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
    check-keys: false
  
  braces:
    max-spaces-inside: 1
  
  brackets:
    max-spaces-inside: 1

ignore: |
  .github/
  node_modules/
  venv/
  .venv/
