apiVersion: rkeprep/v2
kind: AddServer
metadata:
  name: cotpakube02
spec:
  disable-default-system-registry: true
  hostname: cotpakube02
  # Bind to cluster communication interface
  nodeIp: 172.16.15.102
  bindAddress: 172.16.15.102
  advertiseAddress: 172.16.15.102
  cni:
   - multus
   - canal
  interfaces:
    # vlan9
    - name: eth0
      ip: 172.16.15.102
      prefix: 24
      gateway: 172.16.15.1
      dns: ["172.16.10.11", "172.16.10.12"]
      searchDomains: ["k8.cantrellcloud.net","cantrellcloud.net", "cantrelloffice.cloud"]
    # vlan30 - cocloud-ad
    - name: eth1
      ip: 172.16.8.212
      prefix: 24
      gateway:
      dns:
      searchDomains: ["cantrelloffice.cloud", "cantrell.cloud"]
    # vlan10 - cotpa_pub10
    - name: eth2
      ip: 172.16.1.102
      prefix: 24
      gateway:
      dns: ["172.16.1.11", "172.16.1.12"]
      searchDomains: ["cantrelloffice.home", "cantrelloffice.com"]
  node-label:
  - "env=production"
  tls-san:
    - cotpakube02
    - cotpakube02.k8.cantrellcloud.net
    - cotpakube
    - cotpakube.cantrellcloud.net
    - 172.16.15.102
  service-cidr: 10.1.0.0/16
  cluster-cidr: 10.101.0.0/16
  cluster-domain: cluster.local
  enable-servicelb: "false"
  kube-apiserver-arg:
    - "audit-log-maxage=15"
  serverURL: https://172.16.15.101:9345
  tokenFile: /rke2-node-init/outputs/cocloud-ca-chain-bootstrap-token.txt
  disable:
  - rke2-ingress-nginx
  customCA:
    rootCrt: /rke2-node-init/configs/cotpa/certs/cocloud-ca.crt
    rootKey: /rke2-node-init/configs/cotpa/certs/cocloud-ca-key.pem
    intermediateCrt: /rke2-node-init/configs/cotpa/certs/cocloud-issue-ca2.crt
    intermediateKey: /rke2-node-init/configs/cotpa/certs/cocloud-issue-ca2-key.pem
    installToOSTrust: true
