apiVersion: rkeprep/v1
kind: AddServer
metadata:
  name: j52domain-ctrl02
spec:
  ip: 10.0.4.162
  prefix: 24
  gateway: 10.0.4.1
  hostname: j52domain-ctrl02
  dns: ["10.0.1.34", "10.231.1.34"]
  searchDomains: ["dev.kube", "dev.local"]
  node-taint:
  - "node-role.kubernetes.io/control-plane:NoSchedule"
  node-label:
  - "env=preprod"
  tls-san:
    - j52domain-ctrl02
    - j52domain-ctrl02.dev.kube
    - j52domain-cluster
    - j52domain-cluster.dev.kube
    - 10.0.4.162
  service-cidr: 10.96.0.0/16
  cluster-cidr: 10.246.0.0/16
  cluster-domain: cluster.local
  enable-servicelb: "false"
  kube-apiserver-arg:
    - "audit-log-maxage=15"
  serverURL: https://10.0.4.161:9345
  tokenFile: /rke2-node-init/outputs/j52domain-ca-bootstrap-token.txt
  customCA:
    rootCrt: /opt/rke2/stage/certs/dev-certa001-ca-dev-local.crt
    rootKey: /opt/rke2/stage/certs/dev-certa001-ca-dev-local-key.pem
    installToOSTrust: true
  disable:
  - rke2-ingress-nginx
