apiVersion: rkeprep/v1
kind: Agent
metadata:
  name: j64domain-work03
spec:
  ip: 10.0.4.147
  prefix: 24
  gateway: 10.0.4.1
  hostname: j64domain-work03
  dns: ["10.0.1.34", "10.231.1.34"]
  searchDomains: ["dev.kube", "dev.local"]
  serverURL: https://10.0.4.141:9345
  tokenFile: /rke2-node-init/outputs/j64domain-ca-bootstrap-token.txt
  node-label:
  - "role=worker"
  - "env=preprod"