apiVersion: rkeprep/v2
kind: Server
metadata:
  name: dc1domain-ctrl01
spec:
  hostname: dc1domain-ctrl01
  # Bind to cluster communication interface
  nodeIp: 172.16.15.106
  bindAddress: 172.16.15.106
  advertiseAddress: 172.16.15.106
  cni:
   - multus
   - canal
  interfaces:
    # vlan9
    - name: eth0
      ip: 172.16.15.106
      prefix: 24
      gateway: 172.16.15.1
      dns: ["172.16.10.11", "172.16.10.12"]
      searchDomains: ["k8.cantrellcloud.net","cantrellcloud.net"]
    # vlan30 - cocloud-ad
    - name: eth1
      ip: 172.16.8.106
      prefix: 24
      gateway:
      dns:
      searchDomains: ["cantrelloffice.cloud", "cantrell.cloud"]
    # vlan10 - cotpa_pub10
    - name: eth2
      ip: 172.16.1.106
      prefix: 24
      gateway:
      dns: ["172.16.1.11", "172.16.1.12"]
      searchDomains: ["cantrelloffice.home", "cantrelloffice.com"]
  node-label:
  - "env=production"
  tokenFile: /etc/rancher/rke2/token.d/bootstrap.token
  customCA:
    rootCrt: /rke2-node-init/configs/cotpa/certs/cocloud-ca.crt
    rootKey: /rke2-node-init/configs/cotpa/certs/cocloud-ca-key.pem
    intermediateCrt: /rke2-node-init/configs/cotpa/certs/cocloud-issue-ca2.crt
    intermediateKey: /rke2-node-init/configs/cotpa/certs/cocloud-issue-ca2-key.pem
    installToOSTrust: true
  disable:
  - rke2-ingress-nginx
  - rke2-traefik
  tls-san:
    - dc1domain-ctrl01
    - dc1domain-ctrl01.k8.cantrellcloud.net
    - dc1domain-cluster
    - dc1domain.cantrellcloud.net
    - 172.16.15.106
  service-cidr: 10.2.0.0/16
  cluster-cidr: 10.102.0.0/16
  cluster-domain: cluster.local
  enable-servicelb: "false"
  kube-apiserver-arg:
    - "audit-log-maxage=15"
  disable-default-system-registry: true
