apiVersion: rkeprep/v2
kind: Image
metadata:
  name: image-hyperv-rkedomain-v1.35.6+rke2r1
spec:
  rke2Version: v1.35.6+rke2r1
  cni:
   - multus
   - canal
  fixCNIPermissions: false
  embedded-registry: true
  disable-default-registry-endpoint: true
  defaultDns: [172.16.10.11, 172.16.10.12]
  defaultSearchDomains: [k8.cantrellcloud.net, cantrellcloud.net]
  customCA:
    rootCrt: /rke2-node-init/configs/rkedomain-cluster/certs/cocloud-ca.crt
    rootKey: /rke2-node-init/configs/rkedomain-cluster/certs/cocloud-ca-key.pem
    intermediateCrt: /rke2-node-init/configs/rkedomain-cluster/certs/cocloud-issue-ca2.crt
    intermediateKey: /rke2-node-init/configs/rkedomain-cluster/certs/cocloud-issue-ca2-key.pem
    installToOSTrust: true
  bootService:
    enabled: true
    yamlPath: configs/rkedomain-cluster/nodes
    mode: oneshot
    platform: hyperv
