apiVersion: rkeprep/v2
kind: Server
metadata:
  name: cotpa-k8admin
spec:
  disable-default-system-registry: true
  hostname: cotpa-k8admin
  # Bind to cluster communication interface
  nodeIp: 172.16.15.121
  bindAddress: 172.16.15.121
  advertiseAddress: 172.16.15.121
  cni:
   - multus
   - canal
  interfaces:
    # vlan9 - management
    - name: eth0
      ip: 172.16.15.121
      prefix: 24
      gateway: 172.16.15.1
      dns: ["172.16.10.11", "172.16.10.12"]
      searchDomains: ["k8.cantrellcloud.net","cantrellcloud.net"]
    # vlan30 - cocloud-ad
    - name: eth1
      ip: 172.16.8.211
      prefix: 24
      gateway:
      dns:
      searchDomains: ["cantrelloffice.cloud", "cantrell.cloud"]
    # vlan210 - jtodev-ad
    - name: eth2
      ip: 172.16.210.11
      prefix: 27
      gateway:
      dns: 
      searchDomains: 
  node-label:
  - "env=prod"
  tls-san:
    - cotpa-k8admin
    - cotpa-k8admin.k8.cantrellcloud.net
    - 172.16.15.121
  service-cidr: 10.94.0.0/16
  cluster-cidr: 10.244.0.0/16
  cluster-domain: cluster.local
  enable-servicelb: "false"
  kube-apiserver-arg:
    - "audit-log-maxage=15"
  tokenFile: /etc/rancher/rke2/token.d/bootstrap.token
  disable:
  - rke2-ingress-nginx
  customCA:
    rootCrt: /rke2-node-init/configs/cotpa/certs/cocloud-ca.crt
    rootKey: /rke2-node-init/configs/cotpa/certs/cocloud-ca-key.pem
    intermediateCrt: /rke2-node-init/configs/cotpa/certs/cocloud-issue-ca2.crt
    intermediateKey: /rke2-node-init/configs/cotpa/certs/cocloud-issue-ca2-key.pem
    installToOSTrust: true
