apiVersion: rkeprep/v2
kind: Image
metadata:
  name: preprod-vmware-v1.35.2+rke2r1-image
spec:
  rke2Version: v1.35.2+rke2r1
  cni:
   - multus
   - canal
  fixCNIPermissions: false
  registry: altregistry.dev.kube:8443/rke2
  embedded-registry: true
  disable-default-registry-endpoint: true
  defaultDns: [4.2.2.2]
  defaultSearchDomains: [dev.kube, dev.local]
#  customCA:
#    rootCrt: /rke2-node-init/certs/scripts/outputs/root-ca/root-ca.crt
#    rootKey: /rke2-node-init/certs/scripts/outputs/root-ca/root-ca-key.pem
#    intermediateCrt:
#    intermediateKey:
#    installToOSTrust: true
  bootService:
    enabled: false
  #  yamlPath: configs/preprod/nodes
    mode: oneshot
    platform: vmware
