apiVersion: rkeprep/v2
kind: Image
metadata:
  name: cotpa-hyperv-image
spec:
  rke2Version: v1.35.0+rke2r3
  rke2CNIVersion: v1.9.0-build20260116
  rke2MultusVersion: v4.2.3-build20260116
  cni:
   - multus
   - canal
  fixCNIPermissions: false
  registry: kuberegistry.k8.cantrellcloud.net:8443/rke2
  embedded-registry: true
  disable-default-registry-endpoint: true
  defaultDns: [172.16.10.11, 172.16.10.12]
  defaultSearchDomains: [k8.cantrellcloud.net, cantrellcloud.net, cantrelloffice.cloud]
  customCA:
    rootCrt: /rke2-node-init/certs/scripts/outputs/root-ca/root-ca.crt
    rootKey: /rke2-node-init/certs/scripts/outputs/root-ca/root-ca-key.pem
    intermediateCrt:
    intermediateKey:
    installToOSTrust: true
  bootService:
    enabled: false
  #  yamlPath: configs/cotpa/nodes
    mode: oneshot
    platform: hyperv
