apiVersion: rkeprep/v1
kind: AddServer
metadata:
  name: cotpa-ctrl02
spec:
  disable-default-system-registry: true
  hostname: cotpa-ctrl02
  # Bind to cluster communication interface
  nodeIp: 172.16.15.102
  bindAddress: 172.16.15.102
  advertiseAddress: 172.16.15.102
  cni:
   - multus
   - canal
  interfaces:
    - name: eth0
      ip: 172.16.15.102
      prefix: 24
      gateway: 172.16.15.1
      dns: ["172.16.10.11", "172.16.10.12"]
      searchDomains: ["k8.cantrellcloud.net","cantrellcloud.net", "cantrelloffice.cloud"]
  node-taint:
  - "node-role.kubernetes.io/control-plane:NoSchedule"
  node-label:
  - "env=preprod"
  tls-san:
    - cotpa-ctrl02
    - cotpa-ctrl02.cantrellcloud.net
    - cotpa-cluster
    - cotpa-cluster.cantrellcloud.net
    - 172.16.15.102
  service-cidr: 10.93.0.0/16
  cluster-cidr: 10.243.0.0/16
  cluster-domain: cluster.local
  enable-servicelb: "false"
  kube-apiserver-arg:
    - "audit-log-maxage=15"
  serverURL: https://172.16.15.101:9345
  tokenFile: /rke2-node-init/configs/cotpa-ca-bootstrap-token.txt
  disable:
  - rke2-ingress-nginx
