apiVersion: rkeprep/v2
kind: Server
metadata:
  name: dc1rkedev-ctrl01
spec:
  hostname: dc1rkedev-ctrl01
  # Bind to cluster communication interface
  nodeIp: 172.16.210.11
  bindAddress: 172.16.210.11
  advertiseAddress: 172.16.210.11
  cni:
   - multus
   - canal
  interfaces:
    # vlan210
    - name: eth0
      ip: 172.16.210.11
      prefix: 27
      gateway: 172.16.210.1
      dns: ["172.16.10.11", "172.16.10.12"]
      searchDomains: ["k8.cantrellcloud.net", "cantrellcloud.net", "cantrelloffice.cloud", "cantrell.cloud"]
  node-label:
  - "env=production"
  tokenFile: /rke2-node-init/outputs/hyperv-dc1rkedev-cluster-image-bootstrap-token.txt
  customCA:
    rootCrt: /rke2-node-init/configs/dc1rkedev-cluster/certs/cocloud-ca.crt
    rootKey: /rke2-node-init/configs/dc1rkedev-cluster/certs/cocloud-ca-key.pem
    intermediateCrt: /rke2-node-init/configs/dc1rkedev-cluster/certs/cocloud-issue-ca2.crt
    intermediateKey: /rke2-node-init/configs/dc1rkedev-cluster/certs/cocloud-issue-ca2-key.pem
    installToOSTrust: true
  disable:
  - rke2-ingress-nginx
  - rke2-traefik
  tls-san:
    - dc1rkedev-ctrl01
    - dc1rkedev-ctrl01.k8.cantrellcloud.net
    - dc1rkedev-cluster
    - dc1rkedev.cantrellcloud.net
    - 172.16.210.11
  service-cidr: 10.1.0.0/16
  cluster-cidr: 10.101.0.0/16
  cluster-domain: cluster.local
  enable-servicelb: "false"
  kube-apiserver-arg:
    - "audit-log-maxage=15"
  disable-default-system-registry: true
