apiVersion: rkeprep/v2
kind: Agent
metadata:
  name: dc1rkedev-work01
spec:
  hostname: dc1rkedev-work01
  # Bind to cluster communication interface
  nodeIp: 172.16.210.15
  bindAddress: 172.16.210.15
  advertiseAddress: 172.16.210.15
  cni:
   - multus
   - canal
  interfaces:
    # vlan210
    - name: eth0
      ip: 172.16.210.15
      prefix: 27
      gateway: 172.16.210.1
      dns: ["172.16.10.11", "172.16.10.12"]
      searchDomains: ["k8.cantrellcloud.net","cantrellcloud.net", "cantrelloffice.cloud", "cantrell.cloud"]
  node-label:
  - "role=worker"
  - "env=production"
  tokenFile: /rke2-node-init/outputs/hyperv-dc1rkedev-cluster-image-bootstrap-token.txt
  customCA:
    rootCrt: /rke2-node-init/configs/dc1rkedev-cluster/certs/cocloud-ca.crt
    rootKey: /rke2-node-init/configs/dc1rkedev-cluster/certs/cocloud-ca-key.pem
    intermediateCrt: /rke2-node-init/configs/dc1rkedev-cluster/certs/cocloud-issue-ca2.crt
    intermediateKey: /rke2-node-init/configs/dc1rkedev-cluster/certs/cocloud-issue-ca2-key.pem
    installToOSTrust: true
  disable:
  - rke2-ingress-nginx
  - rke2-traefik
  serverURL: https://172.16.210.11:9345
