apiVersion: rkeprep/v2
kind: AddServer
metadata:
  name: cotpa-k802-node03
spec:
  profile: "cis"
  protect-kernel-defaults: true
  hostname: cotpa-k802-node03
  # Bind to cluster communication interface
  nodeIp: 172.16.8.113
  bindAddress: 172.16.8.113
  advertiseAddress: 172.16.8.113
  cni:
   - multus
   - canal
  interfaces:
    # vlan30
    - name: eth0
      ip: 172.16.8.113
      prefix: 24
      gateway: 172.16.8.1
      dns: ["172.16.10.11", "172.16.10.12"]
      searchDomains: ["k8.cantrellcloud.net","cantrellcloud.net", "cantrelloffice.cloud", "cantrell.cloud"]
  node-label:
  - "role=worker"
  - "env=production"
  tls-san:
    - cotpa-k802.k8.cantrellcloud.net
    - cotpa-k802.cantrelloffice.cloud
    - 172.16.8.113
  service-cidr: 10.1.0.0/16
  cluster-cidr: 10.101.0.0/16
  cluster-domain: cluster.local
  enable-servicelb: "false"
    ingress-controller: traefik
  kube-apiserver-arg:
    - "audit-log-maxage=15"
  serverURL: https://172.16.8.111:9345
  tokenFile: /etc/rancher/rke2/token.d/bootstrap.token
  disable:
  - rke2-ingress-nginx
  customCA:
    rootCrt: /rke2-node-init/configs/cotpa-k802-cluster/certs/cocloud-ca.crt
    rootKey: /rke2-node-init/configs/cotpa-k802-cluster/certs/cocloud-ca-key.pem
    intermediateCrt: /rke2-node-init/configs/cotpa-k802-cluster/certs/cocloud-issue-ca2.crt
    intermediateKey: /rke2-node-init/configs/cotpa-k802-cluster/certs/cocloud-issue-ca2-key.pem
    installToOSTrust: true
  disable-default-system-registry: true
  etcd-snapshot-compress: true
  etcd-snapshot-schedule-cron: "0 */6 * * *"
  etcd-snapshot-retention: 14

  secureRegistry: true
  registry: kubeharbor.k8.cantrellcloud.net
  registryUsernameFile: /etc/rancher/rke2/registry-credentials/username
  registryPasswordFile: /etc/rancher/rke2/registry-credentials/token