apiVersion: rkeprep/v2
kind: singleNodeServer
metadata:
  name: rke2-devsingle01
spec:
  clusterMode: single-node
  rke2Version: v1.34.1+rke2r1

  registry: registry.example.internal/rke2
  registryUsername: admin
  registryPassword: CHANGE_ME
  systemDefaultRegistry: registry.example.internal/rke2
  disableDefaultRegistryEndpoint: true

  interfaces:
    - name: ens33
      ip: 10.0.4.31
      prefix: 24
      gateway: 10.0.4.1
      dns:
        - 10.0.1.34
      searchDomains:
        - dev.kube

  nodeName: rke2-devsingle01
  nodeIp: 10.0.4.31
  bindAddress: 10.0.4.31
  advertiseAddress: 10.0.4.31
  writeKubeconfigMode: "0600"

  tls-san:
    - rke2-devsingle01
    - rke2-devsingle01.dev.kube
    - 10.0.4.31

  cni:
    - canal

  node-label:
    - cluster.cantrellcloud.net/mode=single-node-dev
    - topology.kubernetes.io/zone=single-node

  singleNode:
    enabled: true
    mode: dev
    enableCIS: true
    lowResourceAddons: true
    defaultNetworkPolicy: true
    ingressController: none
    snapshotScheduleCron: "0 */12 * * *"
    snapshotRetention: 6
    snapshotDir: /var/lib/rancher/rke2/server/db/snapshots
    auditLogMaxAge: 14
    auditLogMaxBackup: 5
    auditLogMaxSize: 50
